<?php include "cabecalho.php"; ?>

<?php
$Aleatorio = array("JONAS SILVA JATOBA", "    
MARCOS VINÍCIUS SANCHES CARDOSO", "MARIANA DOS SANTOS", "MATHEUS MARQUEZIM GENEBRA", "RAFAEL TSUTAI MASSAKI","REBÉCA RODRIGUES DE OLIVEIRA", "RODOLFO LEONARDO ROMO"   
"RODRIGO MIRANDA DOS SANTOS", "SARAH VITÓRIA PEDROSO DA SILVA", "TAYNA ADRIANA DA SILVA", "VANESSA ALVARES BERNARDO", "VINICIUS GABRIEL GONÇALVES DOS SANTOS",       
"VITOR TAKAYUKI HIROTOMI", "WYLLIAM DOS SANTOS FLORENTINO");


$Ganhador = $Aleatorio[array_rand($Aleatorio)];
echo "<h1>";
echo "Ganhador é: ".$Ganhador;
echo "</h1>";
?>


<?php include "rodape.php"; ?>